Simulation fixed dvl
DukeRobotics/robosub-ros pull request #222
Opened 2020-10-03 03:34 UTC by puzzler7

2020-10-03 15:51 UTC, muthuArivoli requested changes
Here are a couple notes since I can't comment on some files.

What is `comm_code_old.lua`? If it's not going to be used, then please delete it.

The gate model, `Gate.ttm` contains code embedded inside its binary file. I think you can change it to the way you did cthullu, with a single require at the top. Also, try to make capitalization consistent, since cthullu is lowercase, so this should also probably be lowercase.


What is the model `PhysicsRob.ttm`? If it's the same as cthullu, then delete it. Otherwise, remove the code embedded inside it like for `Gate.ttm`.

What is the difference between `RobObstacleCourse.ttt` and `gate_scene.ttt`? Again, if it's not needed then delete it. Also keep capitalization consistent. Also, there is code embedded in the binary file, so move that into its own lua file if you want to keep it.

2020-10-09 07:56 UTC, puzzler7 commented on landside/catkin_ws/src/simulation/scripts/squareCommand.py
> +import thread
Done - threading was used in the first place solely for a "press enter to kill", which is very unnecessary. As such, much of the script has remained the same.

2020-10-09 08:02 UTC, puzzler7 commented
Requested changes have been made.

I replaced the RobWithCam and Gate files entirely, making new ones without embedded code from the currently functional gate_scene. The code that was inside Gate was defunct CV code, and so it has been removed.

As you correctly noticed, many files are old duplicates, and so have been removed.

2020-10-10 05:57 UTC, muthuArivoli requested changes
All comments are about the square command script. Don't worry about it, I'll work on it tonight and merge it before tomorrow, so people can learn the new structure.

2020-10-10 05:57 UTC, muthuArivoli commented on landside/catkin_ws/src/simulation/scripts/squareCommand.py
> +    start = rospy.get_rostime().secs
Just set this to rospy.get_rostime(), subtracting to ros times gives you a duration which you can use to_sec() to convert to a floating point seconds.

2020-10-10 05:57 UTC, muthuArivoli commented on landside/catkin_ws/src/simulation/scripts/squareCommand.py
>      while not a_list:
Use `rospy.is_shutdown()`

2020-10-10 05:57 UTC, muthuArivoli commented on landside/catkin_ws/src/simulation/scripts/squareCommand.py
> +        if rospy.get_rostime().secs - start > 5:
Do `(rospy.get_rostime() - start).to_secs()`

2020-10-10 15:16 UTC, muthuArivoli approved these changes
LGTM

2020-10-10 15:17 UTC, merged