System Usage Package
DukeRobotics/robosub-ros pull request #258
Opened 2021-03-13 18:04 UTC by kyy2

2021-03-16 23:23 UTC, muthuArivoli requested changes
Some changes

2021-03-16 23:23 UTC, muthuArivoli commented on core/catkin_ws/src/custom_msgs/msg/Memory.msg
> +float64 percentage
newline at end

2021-03-16 23:23 UTC, muthuArivoli commented on core/catkin_ws/src/custom_msgs/msg/SystemUsage.msg
> +Memory disk
newline at end

2021-03-16 23:23 UTC, muthuArivoli commented on docker/onboard/Dockerfile
> +
include these in line 28 with pyserial and other pip.
also fix package name

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
rename system_utils

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/launch/pub_system.launch
> +<launch>
rename launch file to system_pub.launch

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/package.xml
> +    Package that publishes system usage information
description to something more generic

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/scripts/system_info_publisher.py
> +        self.disk_memory = Memory()
don't use global variables if you don't have to

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/scripts/system_info_publisher.py
> +    def get_gpu_memory_others(self):
local to function

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/scripts/system_info_publisher.py
> +        self.ram_memory.used = psutil.virtual_memory().total - psutil.virtual_memory().available
return a msg

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/scripts/system_info_publisher.py
> +        self.disk_memory.used = psutil.disk_usage('/').used
return a msg

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/scripts/system_info_publisher.py
> +        rospy.init_node(self.NODE_NAME)
move init_node to init

2021-03-16 23:23 UTC, muthuArivoli commented on onboard/catkin_ws/src/system_usage/scripts/system_info_publisher.py
> +            self._current_msg.header.frame_id = "system_usage_link"
remove frame_id

2021-03-20 17:18 UTC, ShaanGondalia approved these changes
LGTM

2021-03-20 17:22 UTC, muthuArivoli approved these changes
LGTM

2021-03-20 17:24 UTC, merged