Create launch file to automatically determine Arduino port and run se…
DukeRobotics/robosub-ros pull request #270
Opened 2021-03-20 17:28 UTC by ericdjiang

Closes #259

2021-03-23 06:13 UTC, muthuArivoli requested changes
I fixed up the commands, they work when I test on my NUC. Three comments, two of them very trivial, the one critical one is adding this launch file to the motion.launch in the execute package, making sure that it is not run when we want simulation.

2021-03-23 06:13 UTC, muthuArivoli commented on onboard/catkin_ws/src/offboard_comms/README.md
> +roslaunch serial.launch
```suggestion
roslaunch offboard_comms serial.launch
```

2021-03-23 06:13 UTC, muthuArivoli commented on onboard/catkin_ws/src/offboard_comms/launch/serial.launch
> +<launch>
Add the servo_wrapper.py to this launch file, might as well have it integrated with the rest of the system.

Also, add this launch file to one of the launch files in the execute package (maybe motion.launch?). Make sure to not run this when sim=True, however you wish to handle that.

2021-03-24 00:37 UTC, ShaanGondalia approved these changes
LGTM

2021-03-24 03:24 UTC, muthuArivoli approved these changes
LGTM

2021-03-24 03:25 UTC, merged