Foxglove
DukeRobotics/robosub-ros pull request #466
Opened 2023-10-12 00:14 UTC by maxwellmlin

2023-10-18 22:03 UTC, vedarshshah requested changes
Since we are adding an entirely new coding language to our repo (TypeScript), we need to add a linter for it to our GitHub Actions.
- [x] Modify `.github/workflows/linter.yml` to add linter(s) for TS and TSX. Use [this page](https://github.com/super-linter/super-linter) for reference.
- [x] Identify the VS Code extension and settings changes needed to view the linter issues locally (similar to our setup for Python/Flake8) and note this down to be included in a future wiki page. 
- [x] Lint all TS and TSX files accordingly.

The linter should be a part of our GitHub actions before this PR is merged in. Therefore, it may be necessary to create a separate PR to add the linter, merge it in, then merge in this PR.

2023-10-18 23:40 UTC, maxwellmlin commented on foxglove/README.md
> +- [Yarn](https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable)
We use Yarn Classic.

2023-10-19 00:21 UTC, maxwellmlin commented on foxglove/extensions/call-service-panel/CHANGELOG.md
`npm run local-install` requires the extension to have a `README.md` and `CHANGELOG.md`.

2023-10-19 01:32 UTC, maxwellmlin commented on foxglove/extensions/call-service-panel/CHANGELOG.md
We have patched `create-foxglove-extension` to remove this "feature"

2023-10-19 02:03 UTC, maxwellmlin commented on foxglove/README.md
> +
The 3 extensions in this PR are the base extensions

2023-10-19 02:13 UTC, maxwellmlin commented on foxglove/extensions/call-service-panel/package.json
> +  "description": "Example panel that lets you call services",
No, used only for [publishing](https://foxglove.dev/docs/studio/extensions/publish)

2023-10-20 16:13 UTC, maxwellmlin commented
Final changes to make before merge:
- [ ] Try to export all config files to the `foxglove` directory so we can manage the monorepo in one place
- [ ] Resolve dependency conflicts so we can use `npm ci` instead of `npm ci --force`
- [ ] Use the same version of `create-foxglove-extension` across all DRC extensions so that we can apply the same patches
- [ ] Finish adding comments

2023-10-23 21:51 UTC, vedarshshah approved these changes

2023-10-23 23:59 UTC, merged