Nonlinear thrusters allocations
DukeRobotics/robosub-ros pull request #494
Opened 2023-12-14 00:04 UTC by ricohasgithub

- Added the script `thrusters.cpp` to `offboard_comms`, which subscribes the the voltage sensor and thruster force allocation channels
 - We publish the desired PWM allocation given the current voltage and given thruster force allocation via linear interpolation, whereby we leverage several pre-loaded lookup tables storing information on the relation between voltage, force, and PWM

2023-12-15 19:19 UTC, mbryant2025 commented on onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/ThrusterArduino/ThrusterArduino.ino
Should remove unused reference to a publisher

2023-12-15 19:42 UTC, mbryant2025 commented on onboard/catkin_ws/src/offboard_comms/src/thrusters.cpp
Like the implementation here. From my understanding, we are only interpolating between thruster curves to get our PWM. If we really wanted, we could use a greater precision of our voltage (no longer round to 2 places) and interpolate over our individual thruster curves, and then interpolate again between the two curves. Might not be worth it especially if our hardware isn't accurate enough, but just a thought.

2023-12-15 19:57 UTC, mbryant2025 commented on onboard/catkin_ws/src/offboard_comms/src/thrusters.cpp
You define NUM_LOOKUP_ENTRIES in the header file, but do not use it in line 40

2023-12-15 19:59 UTC, mbryant2025 approved these changes
Left a few comments about more semantic things, but functionally seems good

2023-12-21 03:39 UTC, vedarshshah commented on onboard/catkin_ws/src/offboard_comms/src/thrusters.cpp
Just a clarification – we round the _force_ to 2 decimal places, not the voltage; we use full 64-bit floating point precision for the voltage. We lookup the pulse width corresponding to the rounded force in the two thruster power curves for the voltages nearest to the current voltage. Then, we interpolate between the two PWM values using the current voltage, with full `double` precision.

As you indicated, increasing the precision of our force won't help much. Currently, every 0.01 increase in force results in a 2-3 increase in pulse width. So, at most, we could decrease the step size for force to 0.005 to obtain all possible force-to-pulse-width mappings. This is a miniscule difference that won't have much impact on the overall performance of our controls system; there are many other sources of error and inaccuracy that are far greater.

2023-12-30 02:05 UTC, vedarshshah requested changes
All the code looks good. I've modified the documentation and comments and did some minor refactoring.

Two things need to happen for approval:
- [ ] Test refactored code in water.
- [ ] @viethungle-vt1401 Update Thruster Speeds Foxglove panel to subscribe/publish to thruster _allocs_ instead of speeds. This will fix the linter and Foxglove issues.

2024-01-12 04:11 UTC, mbryant2025 commented on onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/ThrusterArduino/ThrusterArduino.ino
> +#define THRUSTER_PWM_OFFSET 31 // Apply offset of +31 for oogway, remove for cthulhu
Finished implementing this functionality in #[edfaa60](https://github.com/DukeRobotics/robosub-ros/pull/494/commits/edfaa60d6ea21ef0aa96234855175c49b54a3ab5) @vedarshshah

2024-01-17 01:39 UTC, vedarshshah requested changes
@mbryant2025 See comments below. Also, update the `offboard_comms` README to mention the changes made regarding how the PWM offset is included.

2024-01-17 01:39 UTC, vedarshshah commented on onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/ThrusterArduino/ThrusterArduino.ino
> +        thrusters[i].write(THRUSTER_STOP_PWM + THRUSTER_PWM_OFFSET);
@mbryant2025 I don't think this loop is necessary as `THRUSTER_STOP_PWM + THRUSTER_PWM_OFFSET` will be written to all thrusters in `loop()`.

2024-01-17 01:39 UTC, vedarshshah commented on onboard/catkin_ws/src/offboard_comms/Arduino Sketchbooks/ThrusterArduino/offset.h
@mbryant2025 Should we commit this file? Or untrack and gitignore it?

2024-01-17 01:39 UTC, vedarshshah commented on onboard/catkin_ws/src/offboard_comms/scripts/dual_upload.sh
> +# onboard/catkin_ws/src/offboard_comms/scripts/copy_offset.sh 0 # Remove the offset file from the compile folder
@mbryant2025 Should this be uncommented?

2024-01-18 01:16 UTC, maxwellmlin commented
Added a commit that closes #502 for thruster allocs.

2024-01-19 02:33 UTC, vedarshshah approved these changes

2024-01-19 02:41 UTC, merged