Refactor Example Extensions
DukeRobotics/robosub-ros pull request #496
Opened 2023-12-23 04:43 UTC by maxwellmlin

2024-01-10 18:45 UTC, vedarshshah requested changes
Several nice-to-have things. Will discuss in-person what we want to implement and what we want to save for later.

2024-01-12 02:21 UTC, maxwellmlin commented on foxglove/extensions/publish-topic-panel/src/PublishTopicPanel.tsx
See https://github.com/DukeRobotics/robosub-ros/issues/499

2024-01-12 02:21 UTC, maxwellmlin commented on foxglove/extensions/publish-topic-panel/src/PublishTopicPanel.tsx
See https://github.com/DukeRobotics/robosub-ros/issues/499

2024-01-12 02:21 UTC, maxwellmlin commented on foxglove/extensions/publish-topic-panel/src/PublishTopicPanel.tsx
See https://github.com/DukeRobotics/robosub-ros/issues/499

2024-01-12 02:22 UTC, maxwellmlin commented on foxglove/extensions/call-service-panel/src/CallServicePanel.tsx
Decided `undefined` is OK

2024-01-12 02:22 UTC, maxwellmlin commented on foxglove/extensions/subscribe-topic-panel/src/SubscribeTopicPanel.tsx
Decided `undefined` is OK

2024-01-12 02:24 UTC, vedarshshah approved these changes

2024-01-12 02:25 UTC, merged